name: split_free
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  components:
    path: 'packages/components'

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.5
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.13
  google_fonts: ^2.1.0
  line_icons: ^2.0.1
  pinput: ^2.2.7
  month_picker_dialog: ^0.4.0
  fl_chart: ^0.50.1
  csc_picker: ^0.2.6
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  connectivity: ^3.0.6
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
